services:
  postgres_order:
    image: postgres:15-alpine
    container_name: wb-postgres-order
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data

  postgres_management:
    image: postgres:15-alpine
    container_name: wb-postgres-manufacturing
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manufacturing
    ports:
      - "5433:5432"
    volumes:
      - postgres_management_data:/var/lib/postgresql/data

volumes:
  postgres_order_data:

  postgres_management_data: